=== KIMGEONUNG/CoverageReporter/config_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for my JSON file format",

  "type": "object",

  "properties": {
    "report_generator_path": {
      "type": "string",
      "description": "ReportGenerator.exe path"
    },
    "open_cover_path": {
      "type": "string",
      "description": "OpenCover.Console.exe path"
    },
    "vs_test_path": {
      "type": "string",
      "description": "vstest.console.exe path"
    },
    "coverage_path": {
      "type": "string",
      "description": "This is for folder to save OpenCover result"
    },
    "report_path": {
      "type": "string",
      "description": "This is for folder to save ReportGenerator result"
    }
  },
  "required": [ "coverage_path", "open_cover_path", "report_generator_path", "report_path", "vs_test_path" ]
}

=== KIMGEONUNG/CoverageReporter/config.json
{
  "report_generator_path": "C:\\ReportGenerator_4.4.0\\net47\\ReportGenerator.exe",
  "open_cover_path": "C:\\Users\\saywo\\AppData\\Local\\Apps\\OpenCover\\OpenCover.Console.exe",
  "vs_test_path": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe",
  "coverage_path": "C:\\converage",
  "report_path": "C:\\converage_report"
}
